// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLV8H_-9QRX_ZecXQGGExwXPd14YBwzjY',
    appId: '1:885334297157:web:3a66d7fac1fe37c0dd312c',
    messagingSenderId: '885334297157',
    projectId: 'shopapp-bdd2c',
    authDomain: 'shopapp-bdd2c.firebaseapp.com',
    storageBucket: 'shopapp-bdd2c.firebasestorage.app',
    measurementId: 'G-K65G9GQCZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqqHMJ90uB8wKI6z-2P8slhyCVfxrueA',
    appId: '1:885334297157:android:764e21d93d7d0353dd312c',
    messagingSenderId: '885334297157',
    projectId: 'shopapp-bdd2c',
    storageBucket: 'shopapp-bdd2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQjapHNRdfNvl9caeY5DtqFneGnLL6fc',
    appId: '1:885334297157:ios:40c6e3ebc49ca4a7dd312c',
    messagingSenderId: '885334297157',
    projectId: 'shopapp-bdd2c',
    storageBucket: 'shopapp-bdd2c.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQjapHNRdfNvl9caeY5DtqFneGnLL6fc',
    appId: '1:885334297157:ios:40c6e3ebc49ca4a7dd312c',
    messagingSenderId: '885334297157',
    projectId: 'shopapp-bdd2c',
    storageBucket: 'shopapp-bdd2c.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLV8H_-9QRX_ZecXQGGExwXPd14YBwzjY',
    appId: '1:885334297157:web:ebc1359782904adedd312c',
    messagingSenderId: '885334297157',
    projectId: 'shopapp-bdd2c',
    authDomain: 'shopapp-bdd2c.firebaseapp.com',
    storageBucket: 'shopapp-bdd2c.firebasestorage.app',
    measurementId: 'G-KQNYQ157XG',
  );
}
